name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "sa-east-1"

      - name: Terraform network
        run: |
          terraform -chdir=network init
          # terraform -chdir=network plan -out=network-tfplan
          # terraform -chdir=network apply -auto-approve network-tfplan

      - name: Terraform certificates
        run: |
          terraform -chdir=certificates init
          # terraform -chdir=certificates plan -out=certificates-tfplan
          # terraform -chdir=certificates apply -auto-approve certificates-tfplan

      - name: Terraform api
        run: |
          terraform -chdir=api init
          # terraform -chdir=api plan -out=api-tfplan
          # terraform -chdir=api apply -auto-approve api-tfplan
